// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CompactTreeExplorer.tsx": () => import("../components/mockups/CompactTreeExplorer.tsx"),
  "./components/mockups/lore-consolidated-v2/AlbumLorePanel.tsx": () => import("../components/mockups/lore-consolidated-v2/AlbumLorePanel.tsx"),
  "./components/mockups/lore-consolidated-v2/HomeScreen.tsx": () => import("../components/mockups/lore-consolidated-v2/HomeScreen.tsx"),
  "./components/mockups/lore-consolidated-v2/LoreChip.tsx": () => import("../components/mockups/lore-consolidated-v2/LoreChip.tsx"),
  "./components/mockups/lore-consolidated-v2/RunDrawer.tsx": () => import("../components/mockups/lore-consolidated-v2/RunDrawer.tsx"),
  "./components/mockups/lore-grayscale/LoreGrayscale.tsx": () => import("../components/mockups/lore-grayscale/LoreGrayscale.tsx"),
  "./components/mockups/lore-on-air-record-piles/LoreOnAirRecordPiles.tsx": () => import("../components/mockups/lore-on-air-record-piles/LoreOnAirRecordPiles.tsx"),
  "./components/mockups/lore-home/LibraryFirst.tsx": () => import("../components/mockups/lore-home/LibraryFirst.tsx"),
  "./components/mockups/lore-home/NowFirst.tsx": () => import("../components/mockups/lore-home/NowFirst.tsx"),
  "./components/mockups/lore-shared-room/SharedRoomDesktop.tsx": () => import("../components/mockups/lore-shared-room/SharedRoomDesktop.tsx"),
  "./components/mockups/lore-shared-room/SharedRoomMobile.tsx": () => import("../components/mockups/lore-shared-room/SharedRoomMobile.tsx"),
  "./components/mockups/lore-slack/AmbientCard.tsx": () => import("../components/mockups/lore-slack/AmbientCard.tsx"),
  "./components/mockups/lore-slack/CommandCard.tsx": () => import("../components/mockups/lore-slack/CommandCard.tsx"),
  "./components/mockups/lore-slack/UnfurlCard.tsx": () => import("../components/mockups/lore-slack/UnfurlCard.tsx"),
  "./components/mockups/lore-timeline-queue/TimelineQueueDesktop.tsx": () => import("../components/mockups/lore-timeline-queue/TimelineQueueDesktop.tsx"),
  "./components/mockups/lore-timeline-queue/TimelineQueueMobile.tsx": () => import("../components/mockups/lore-timeline-queue/TimelineQueueMobile.tsx"),
  "./components/mockups/lore-unified-arch/UnifiedArch.tsx": () => import("../components/mockups/lore-unified-arch/UnifiedArch.tsx"),
  "./components/mockups/music-explore/TheCaseFile.tsx": () => import("../components/mockups/music-explore/TheCaseFile.tsx"),
  "./components/mockups/music-explore/TheMap.tsx": () => import("../components/mockups/music-explore/TheMap.tsx"),
  "./components/mockups/music-explore/TheThread.tsx": () => import("../components/mockups/music-explore/TheThread.tsx"),
  "./components/mockups/playhead/PlayheadDesktop.tsx": () => import("../components/mockups/playhead/PlayheadDesktop.tsx"),
  "./components/mockups/playhead/PlayheadMobile.tsx": () => import("../components/mockups/playhead/PlayheadMobile.tsx"),
  "./components/mockups/playhead-unified/OneSpineDesktop.tsx": () => import("../components/mockups/playhead-unified/OneSpineDesktop.tsx"),
  "./components/mockups/playhead-unified/OneSpineMobile.tsx": () => import("../components/mockups/playhead-unified/OneSpineMobile.tsx")
};
